# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_url', models.CharField(max_length=255, unique=True, verbose_name='From URL')),
                ('to_url', models.CharField(max_length=255, verbose_name='To URL')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'URL Redirects',
            },
        ),
    ]
