# Generated by Django 4.2.24 on 2025-09-30 12:18

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_titles_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='large_photo',
            field=models.ImageField(help_text='Best 1280x532', upload_to='lawyers', verbose_name='Large Photo'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='profile_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Cropped to 200x200', upload_to='lawyers', verbose_name='Small Profile Photo'),
        ),
    ]
