# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 16:19
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170131_1819'),
        ('mailinglists', '0005_mailinglist_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'proxy': True,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='ctype',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'articles'), (2, 'news'), (3, 'computer_law'), (4, 'legislation')], null=True, verbose_name='List for Content Type'),
        ),
    ]
