# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0006_auto_20170131_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='full_content',
            field=models.BooleanField(default=False, help_text='Send full content of items', verbose_name='Full Content'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='ctype',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'articles'), (2, 'news'), (3, 'computer_law'), (4, 'legislation')], help_text='Leave empty for all content types', null=True, verbose_name='List for Content Type'),
        ),
    ]
