# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0007_auto_20170425_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='mailing_lists', to='content.ContentCategory', verbose_name='Topics'),
        ),
    ]
