# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 07:56
from __future__ import unicode_literals

from django.db import migrations


def set_about_template(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    Page.objects.filter(slug__in=('about', 'about-group')).update(
        template='pages/page_with_about_sidebar.html')


def unset_about_template(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    Page.objects.filter(slug__in=('about', 'about-group')).update(
        template=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_template'),
    ]

    operations = [
        migrations.RunPython(set_about_template,
                             reverse_code=unset_about_template)
    ]
