# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 16:01
from __future__ import unicode_literals

from django.db import migrations

PAGES = [
    {
        'language': 'he',
        'title': 'עדכונים מהאתר',
        'slug': 'updates',
        'content': '''
<p>
law.co.il לא רכושני לגבי גולשיו. כלומר, אם האתר מוצא חן בעיניך אבל לא בא לך לפתוח דפדפן -- או שאת/ה מת לבדוק מה חדש דווקא באמצע השום-כלום כשרק הטלפון הסלולרי אתך -- אנחנו מגיעים אליך בכל אחת מהדרכים הבאות:
</p>
<ul>
    <li><a href="/my/settings"><strong>בדואר אלקטרוני</strong></a>:
    <ul>
        <li><strong>רשימות הדיוור</strong> של law.co.il נשלחות אחת לשבוע (רובן) וכוללות את כל עדכוני החדשות והפסיקה מהאתר. אם רק בחלק מהעדכונים מעניינים אותך, אפשר להירשם לרשימת-דיוור העוסקת בנושאים מסוימים (לדוגמה, אבטחת מידע ופרטיות או קנין רוחני). עדכוני היומן הדיגיטלי יביאו אליך את כל פסקי הדין החדשים שניתנו בישראל בנושאי מחשבים ואינטרנט.</li>
        <li><strong>ההתראות</strong> מאפשרות לך לקבוע איזו מילה מעניינת אותך. רוצה לדעת ממש ברגע שאנחנו מוסיפים מילים מסוימות לאתר? ניתן לקבל הודעה בדואר אלקטרוני כאשר מתפרסמים ידיעה או מאמר המכילים מילה או ביטוי. כל מה שנדרש הוא לציין את המילים שברצונך לעקוב אחריהם.</li>
    </ul>
    </li>
    <li><a href="https://itunes.apple.com/il/app/law.co.il/id469819834?mt=8"><strong>באייפון</strong></a>: אפליקציה מיוחדת למשתמשי אייפון (והיא הפתרון למי שמתלוננים שגרסת הסלולר היא בלתי גלילה בדפדן של Apple iOS).</li>
    <li><a href="http://www.facebook.com/law.co.il"><strong>בפייסבוק</strong></a>: חדשות, עדכוני פסיקה וכל דבר אחר שבא לנו מתעדכן בפייסבוק. לא ממש אוטומטי (מבחירה) ולא במהירות הרבה ביותר, אבל זה שם וכל מה שצריך הוא לעשות לייק ל<a href="http://www.facebook.com/law.co.il">עמוד שלנו</a>.</li>
    <li><a href="http://twitter.com/lawcoil"><strong>בטוויטר</strong></a><strong>:</strong>  חדשות, עדכוני פסיקה ומאמרים עולים מידית גם ל- Twitter, מה שמאפשר לך  לקרוא אותם בדף הטוויטר שלך או בתוכנה שבה את/ה קורא טוויטים. לשם כך, כל  מה שצריך הוא להירשם בטוויטר <a href="http://twitter.com/lawcoil">לפיד של law.co.il</a> (בחינם, לא צריך להגיד).</li>
    <li><a href="/rss/"><strong>עדכוני RSS:</strong></a> כל מה שעולה לאתר, מופיע גם בתזרימי רסס (עברית ל- RSS Feeds). כל מה שנחוץ הוא להוסיף את הפיד לקורא ה- RSS החביב עליך (תוכנה, אתר או whatever) - ובזה נגמר העניין. מה שהופיע באתר, יופיע גם אצלך. אפשר להירשם לקטגוריה ראשית (לדוגמה: <a href="/rss/news/">חדשות</a>) ואפשר גם לעקוב רק אחרי הנושאים שמעניינים אותך (לדוגמה: <a href="/rss/news/open-source/">קוד פתוח</a> או <a href="/rss/computer-law/">עדכוני חקיקה בתחום המחשבים</a>).</li>
</ul>
בהנאה.<br />
        '''
    },
]


def load_pages(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    pages = [Page(**page) for page in PAGES]
    Page.objects.bulk_create(pages)


def unload_pages(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    slugs = set([x['slug'] for x in PAGES])
    Page.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_about-pages-template'),
    ]

    operations = [
        migrations.RunPython(load_pages, reverse_code=unload_pages)
    ]
