# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-20 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation',
        ),
    ]
