# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-20 09:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_remove_annotation_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Annotation object'),
        ),
    ]
