# Generated by Django 4.2.24 on 2025-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_annotation_annotation_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_object',
            field=models.JSONField(default=dict, verbose_name='Annotation object'),
        ),
    ]
