# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models

CATEGOROIES = [
    {'color': '#d9707d',
     'icon_css_class': 'privacy-security-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'פרטיות ואבטחת מידע',
     'slug': 'privacy-security'},
    {'color': '#999999',
     'icon_css_class': 'apple-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'אפל',
     'slug': 'apple'},
    {'color': '#3a5163',
     'icon_css_class': 'google-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'גוגל',
     'slug': 'google'},
    {'color': '#f09c1e',
     'icon_css_class': 'copyright-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'זכויות יוצרים',
     'slug': 'copyright'},
    {'color': '#c73f35',
     'icon_css_class': 'spam-email-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'ספאם ודואל',
     'slug': 'spam-email'},
    {'color': '#8c1e68',
     'icon_css_class': 'opinions-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'דעות',
     'slug': 'opinions'},
    {'color': '#47bd9c',
     'icon_css_class': 'gambling-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'הימורים',
     'slug': 'gambling'},
    {'color': '#f05c5c',
     'icon_css_class': 'freedom-of-speech-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'חופש הביטוי',
     'slug': 'freedom-of-speech'},
    {'color': '#4273ba',
     'icon_css_class': 'microsoft-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'מיקרוסופט',
     'slug': 'microsoft'},
    {'color': '#5e993f',
     'icon_css_class': 'regulation-government-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'רגולציה וממשל',
     'slug': 'regulation-government'},
    {'color': '#bd9e2e',
     'icon_css_class': 'civil-procedure-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'סדר דין אזרחי',
     'slug': 'civil-procedure'},
    {'color': '#75b842',
     'icon_css_class': 'criminal-procedure-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'סדר דין פלילי',
     'slug': 'criminal-procedure'},
    {'color': '#eb1e8f',
     'icon_css_class': 'visitors-exposure-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'חשיפת גולשים',
     'slug': 'visitors-exposure'},
    {'color': '#35a3b8',
     'icon_css_class': 'ecommerce-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'מסחר אלקטרוני',
     'slug': 'ecommerce'},
    {'color': '#2b2b2b',
     'icon_css_class': 'trademarks-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'סימני מסחר',
     'slug': 'trademarks'},
    {'color': '#f05c21',
     'icon_css_class': 'sex-porn-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'מין ופורנוגרפיה',
     'slug': 'sex-porn'},
    {'color': '#074a78',
     'icon_css_class': 'facebook-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'פייסבוק',
     'slug': 'facebook'},
    {'color': '#7f94cc',
     'icon_css_class': 'open-source-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'קוד פתוח',
     'slug': 'open-source'},
    {'color': '#947d61',
     'icon_css_class': 'electronic-evidence-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'ראיות אלקטרוניות',
     'slug': 'electronic-evidence'},
    {'color': '#ab512e',
     'icon_css_class': 'domain-names-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'שמות מתחם',
     'slug': 'domain-names'},
    {'color': '#70b8e6',
     'icon_css_class': 'communication-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'תקשורת',
     'slug': 'communication'},
    {'color': '#555555',
     'icon_css_class': 'misc-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'שונות',
     'slug': 'misc'},
    {'color': '#d9707d',
     'icon_css_class': '',
     'is_hot': False,
     'language': 'en',
     'name': 'Israeli Internet Law Update',
     'slug': 'israeli-internet-law-update'},
    {'color': '#8F4C9C',
     'icon_css_class': 'patents-icon',
     'is_hot': True,
     'language': 'he',
     'name': 'פטנטים',
     'slug': 'patents'},
    {'color': '#783D54',
     'icon_css_class': 'computer-crime-icon',
     'is_hot': True,
     'language': 'he',
     'name': 'פשעי מחשב',
     'slug': 'computer-crime'},
    {'color': '#1e8f6e',
     'icon_css_class': 'labor-employment-law-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'דיני עבודה',
     'slug': 'labor-employment-law'},
    {'color': '#267375',
     'icon_css_class': 'commercial-torts-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'עוולות מסחריות',
     'slug': 'commercial-torts'},
    {'color': '#3C3164',
     'icon_css_class': 'suppliers-liability-icon',
     'is_hot': False,
     'language': 'he',
     'name': 'אחריות ספקים',
     'slug': 'suppliers-liability'}
]


def load_categories(apps, schema_editor):
    ContentCategory = apps.get_model('content', 'ContentCategory')
    categories = [ContentCategory(**cat) for cat in CATEGOROIES]
    ContentCategory.objects.bulk_create(categories)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_categories)
    ]
