# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 09:51
from __future__ import unicode_literals

from django.db import migrations


def change_internet_law_update_category(apps, schema_editor):
    ContentCategory = apps.get_model('content', 'ContentCategory')
    cat = ContentCategory.objects.get(slug='israeli-internet-law-update')
    cat.slug = 'internet-law-update'
    cat.name = 'Internet Law Update'
    cat.save()


def restore_internet_law_update_category(apps, schema_editor):
    ContentCategory = apps.get_model('content', 'ContentCategory')
    cat = ContentCategory.objects.get(slug='internet-law-update')
    cat.slug = 'israeli-internet-law-update'
    cat.name = 'Israeli Internet Law Update'
    cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_commoncontent_email_notified'),
    ]

    operations = [
        migrations.RunPython(change_internet_law_update_category,
                             reverse_code=restore_internet_law_update_category)
    ]
