# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_change-internet-law-update-category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
            ],
            options={
                'verbose_name': 'Legislation',
                'verbose_name_plural': 'Legislations',
                'ordering': ['-created_at'],
                'proxy': True,
            },
            bases=('content.commoncontent',),
        ),
        migrations.AlterField(
            model_name='commoncontent',
            name='ctype',
            field=models.PositiveIntegerField(choices=[(1, 'articles'), (2, 'news'), (3, 'computer_law'), (4, 'legislation')], verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='commoncontent',
            name='language',
            field=models.CharField(choices=[('he', 'Hebrew'), ('en', 'English')], db_index=True, default='he', max_length=5, verbose_name='Language'),
        ),
    ]
