# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170119_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncontent',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Published'),
        ),
    ]
