# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170228_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Content Category', 'verbose_name_plural': 'Content Categories'},
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
    ]
