# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170314_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncontent',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='Slug'),
        ),
    ]
