# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-17 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170317_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commoncontent',
            unique_together=set([('language', 'ctype', 'slug')]),
        ),
    ]
