# Generated by Django 4.2.24 on 2025-09-30 12:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0009_alter_contributor_lawyer'),
        ('content', '0013_auto_20180807_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncontent',
            name='contributors',
            field=models.ManyToManyField(related_name='%(class)s', to='contributors.contributor', verbose_name='Contributors'),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
