# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 08:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_contributor_small_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
