# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_auto_20161025_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='show_link',
            field=models.BooleanField(default=False, verbose_name='Show link'),
        ),
    ]
