# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0005_contributor_show_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to author'),
        ),
    ]
