# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0006_contributor_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Contributor', 'verbose_name_plural': 'Contributors'},
        ),
        migrations.AddField(
            model_name='contributor',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, default=10, verbose_name='Order'),
        ),
    ]
