# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_titles_data'),
        ('contributors', '0007_auto_20170124_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.Lawyer', verbose_name='Lawyer'),
        ),
    ]
