# Generated by Django 4.2.24 on 2025-09-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0006_alter_lawyer_large_photo_alter_lawyer_profile_photo'),
        ('contributors', '0008_contributor_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.lawyer', verbose_name='Lawyer'),
        ),
    ]
