# Generated by Django 4.2.24 on 2025-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=24, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=24, null=True)),
                ('op', models.CharField(max_length=1)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('candel', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196)),
                ('date', models.DateField(blank=True, null=True)),
                ('shortdesc', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('contributed', models.CharField(max_length=196)),
                ('lang', models.CharField(max_length=1)),
                ('oftheweek', models.CharField(blank=True, max_length=1, null=True)),
                ('offline', models.CharField(blank=True, max_length=1, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=60, null=True)),
                ('item_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyArticlescat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('root', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('lang', models.CharField(max_length=1)),
                ('catdesc', models.TextField(blank=True, null=True)),
                ('csec', models.CharField(blank=True, max_length=1, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('withtitle', models.CharField(blank=True, max_length=1, null=True)),
                ('in_index', models.CharField(max_length=1)),
                ('in_index_root', models.CharField(max_length=64)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'articlescat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyArticlescatArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'articlescat_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('login', models.CharField(blank=True, max_length=24, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=24, null=True)),
                ('org', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyContribs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('def_field', models.CharField(blank=True, db_column='def', max_length=1, null=True)),
            ],
            options={
                'db_table': 'contribs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engname', models.CharField(max_length=196)),
                ('hebname', models.CharField(max_length=196)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('engdesc', models.TextField(blank=True, null=True)),
                ('hebdesc', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('islinks', models.CharField(max_length=1)),
                ('offline', models.CharField(blank=True, max_length=1, null=True)),
                ('hebsite', models.CharField(blank=True, max_length=1, null=True)),
                ('mainsite', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyLinkscat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('root', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('lang', models.CharField(max_length=1)),
                ('catdesc', models.TextField(blank=True, null=True)),
                ('csec', models.CharField(blank=True, max_length=1, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('in_index', models.CharField(max_length=1)),
                ('in_index_root', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'linkscat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyLinkscatLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'linkscat_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('private', models.SmallIntegerField()),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('send_days', models.IntegerField(blank=True, null=True)),
                ('send_count', models.IntegerField(blank=True, null=True)),
                ('news_category', models.CharField(max_length=128)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('contributed', models.CharField(max_length=196)),
                ('lang', models.CharField(max_length=1)),
                ('offline', models.CharField(blank=True, max_length=1, null=True)),
                ('whatsnew', models.CharField(blank=True, max_length=1, null=True)),
                ('slug', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyNewscat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('lang', models.CharField(max_length=1)),
                ('catdesc', models.TextField(blank=True, null=True)),
                ('bytesdesc', models.IntegerField(blank=True, null=True)),
                ('csec', models.CharField(blank=True, max_length=1, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('root', models.CharField(blank=True, max_length=64, null=True)),
                ('style', models.IntegerField(blank=True, null=True)),
                ('in_index', models.CharField(max_length=1)),
                ('in_index_root', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'newscat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyNewscatNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'newscat_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacySubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('opertype', models.CharField(blank=True, max_length=16, null=True)),
                ('opercode', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('opercode_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.IntegerField()),
                ('words', models.TextField(blank=True, null=True)),
                ('full', models.IntegerField()),
            ],
            options={
                'db_table': 'subscribers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacySubscriberslists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('subscriber_id', models.IntegerField()),
            ],
            options={
                'db_table': 'subscriberslists',
                'managed': False,
            },
        ),
    ]
