# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models

PRACTICES = [
    {'content': '<p>הטמעת מערכות מחשב בעסקים וחברות, השימוש באינטרנט והסחר '
                'האלקטרוני, מעוררים סוגיות משפטיות המשלבות תחומי משפט, שרק לעתים '
                'נדירות נפגשים יחדיו - קניין רוחני, דיני פרטיות, הגנת הצרכן, '
                'מחשבים, חוזים ועוד. השירותים שקבוצת האינטרנט וה-IT ב<a '
                'href="http://www.pczlaw.com">פרל כהן צדק לצר</a> מספקת בתחום זה '
                'כוללים, בין השאר -</p>\r\n'
                '<ul>\r\n'
                '    <li><b>ליווי פרויקטים לסחר אלקטרוני ותוכן</b> מתחילתם (עוד '
                'בשלבי האפיון הראשונים) ועד ליישומם המלא. במסגרת זאת צברו עורכי '
                'הדין בקבוצה ניסיון רב בעריכת חוזים עם ספקי-יישומים, שותפי-תוכן '
                'וספקי מידע ובניהול משא ומתן לחתימתם; בדיקת הסיכונים המשפטיים '
                'הכרוכים בהפעלת המערכות וצמצומם; בדיקת האתרים והתהליכים בהם קודם '
                'להשקתם; ייעוץ ביחס להבטים המשפטיים של אבטחת המידע והפרטיות '
                'במערכות המיושמות ועוד.</li>\r\n'
                '    <li><b>הכנת הסכמים - מקוונים או אחרים - וכן תנאי שימוש '
                'ומדיניות פרטיות לאתרי אינטרנט</b>, בין אם אתרים המופנים ללקוחות '
                'סופיים (C2B) ובין אם אתרים המיועדים לסחר אלקטרוני בין עסקים '
                '(B2B). בכלל זה ממליצה הקבוצה כיצד ליישם את ההסכמים, היכן להעדיף '
                'הסכם מקוון והיכן לבכר הסכם רגיל. בין האתרים שטופלו בידי עורכי '
                'בדין בקבוצה - פורטלים ואתרי סחר אלקטרוני מהגדולים והמובילים '
                'בישראל;</li>\r\n'
                '    <li><b>הסכמים להקמת אתרי ומערכות אינטרנט</b>;</li>\r\n'
                '    <li><b>הסכמי תוכן</b> המיועדים הן לפעילות Web רגילה והן '
                'לפעילות במדיה סלולרית.</li>\r\n'
                '    <li><b>ניהול הליכים משפטיים</b>: בכלל זה ניהלו עורכי הדין '
                'בקבוצה תביעה ראשונה מסוגה שהגיש ספק גישה לאינטרנט נגד צה&quot;ל, '
                'בקשר עם צו שיפוטי שהורה לספק למסור לצבא את תעבורת הדואר '
                'האלקטרוני של מנוייו. הליך תקדימי זה הסתיים בהוראת פרקליטת המדינה '
                'לאמץ חלק ניכר מטענות ספק הגישה ולקבוע שתפיסת הודעות דואר '
                'אלקטרוני שטרם הגיעו למחשבי הספק תבוצע בדרך של צו להאזנת סתר '
                'בלבד. הקבוצה ייצגה ספק גישה אחר בתביעה הראשונה בישראל שהוגשה נגד '
                "'ספאמר' (משגר 'דואר-זבל'). כן היא מייצגת תובעים, שדרשו למנוע "
                'מספק שירותים להשתמש בסימן שהיה זהה לשם מתחם (Domain Name) '
                'שבבעלותם, נתבעים בהליכים למסירת שמות מתחם ועוד.</li>\r\n'
                '    <li><b>מתן חוות דעת</b>: הנושאים שעימם התמודדה הקבוצה בשנים '
                'האחרונות כוללים סיכונים המשפטיים הגלומים בניהול פעילות אינטרנט '
                'או בפיתוח תוכנות מחשב מסוימות; הגנת זכויות יוצרים ורשיונות '
                'הדרושים מבעלי זכויות יוצרים לפעילות אחרת; מותר ואסור בקישור בין '
                'אתרי אינטרנט; היבטים של קניין רוחני בתוכנות מחשב; ההגנה על קניין '
                'רוחני בסביבה הדיגיטלית ורישויו הנכון; יישום דיני הפרטיות והגנת '
                'הצרכן על פעילות סחר אלקטרוני מסוימת; תחולת דיני ההצפנה על פעילות '
                'אחרת; יישום ופירוש רשיונות קוד-פתוח בפיתוח תוכנות ועוד.</li>\r\n'
                '    <li><b>עריכת הסכמי רשיון</b> - בין אם הסכמים אחידים המוטמעים '
                'בתוך תוכנות (Click-Wrap Agreements) ובין אם הסכמים המיועדים '
                'לחתימה בין שני צדדים;</li>\r\n'
                '    <li><b>אכיפה וחיווי דעה בתחום זכויות יוצרים</b>;</li>\r\n'
                '</ul>',
     'language': 'he',
     'order': 0,
     'slug': 'internet-law',
     'title': 'משפט באינטרנט'},
    {'content': '<p>מערכות מחשב, תקשורת וטכנולוגיה מצויות בליבת הפעילות של כל עסק '
                'שהוא. לקבוצת האינטרנט, הסייבר וזכויות היוצרים בפרל כהן צדק לצר '
                'ברץ&nbsp;ניסיון בהכנת ההסכמים הדרושים לרכש, פיתוח ותפעול מערכות '
                'מחשב, מידע וטכנולוגיה ושאר העסקאות הנוגעות לעולם המחשוב. בכלל זה '
                '-</p>\r\n'
                '<ul>\r\n'
                '    <li>ליווי השלבים המוקדמים להתקשרות בעסקה - הכנת <b>RFIs, '
                'RFPs</b> וניהול המשא-ומתן;</li>\r\n'
                '    <li>הסכמים לפיתוח ותחזוקת מערכות תוכנה פנים-ארגוניות, '
                '<b>לרבות מיקור-חוץ</b>;</li>\r\n'
                '    <li>רכש ופיתוח <b>תוכנות</b> המיועדות למכירה בשוק החופשי '
                '(&quot;<b>תוכנות מדף</b>&quot;);</li>\r\n'
                "    <li>הסכמי רישוי ופיתוח לשירותי 'תוכנה כשירות' "
                '(<strong>SaaS</strong>) ומחשוב ענן (<strong>Cloud '
                'Computing</strong>);</li>\r\n'
                '    <li>פיתוח ותחזוקת <b>מערכות משולבות</b> חומרה, תקשורת (Call '
                'Centers) ותוכנה ועוד.</li>\r\n'
                '</ul>\r\n'
                '<p>היקף העסקאות שטופלו במשרד בתחומים אלה נע בין עשרות ומאות אלפי '
                'דולרים למיליוני דולרים.</p>',
     'language': 'he',
     'order': 1,
     'slug': 'computers-and-IT',
     'title': 'מחשבים, מערכות מידע ורכש טכנולוגי'},
    {'content': '<p>במהלך השנים 2000-2001 ליווה עו&quot;ד חיים רביה מקרוב את '
                'תהליך החקיקה של חוק חתימה אלקטרונית. בעת החקיקה עצמה שימש '
                'עו&quot;ד רביה כנציג לשכת עורכי-הדין בישראל לועדת המשנה של הכנסת '
                'שגיבשה את החוק וליווה מקרוב גם אחר גיבוש התקנות.  <br />\r\n'
                '<br />\r\n'
                'המשרד מייצג הן את אחד מבין שני הגורמים המאשרים בישראל הפועלים '
                'על-פי החוק, הן חברות טכנולוגיה ושירות, המפתחות פתרונות לחתימה '
                'אלקטרונית והן גופים הבוחנים אפשרויות להטמעת טכנולוגיות '
                'בתחום.</p>',
     'language': 'he',
     'order': 2,
     'slug': 'e-sig',
     'title': 'חתימה אלקטרונית'},
    {'content': '<p>הקבוצה מייצגת את לקוחות המשרד ומייעצת להם בשורה של נושאים '
                'בתחום התקשורת, לרבות -</p>\r\n'
                '<ul>\r\n'
                '    <li>הגשת <b>הצעות לקביעת מדיניות</b> של משרד התקשורת בנושאים '
                'בעלי אופי טכנולוגי חדשני;</li>\r\n'
                '    <li>ניהול משא ומתן עם משרד התקשורת על תנאי <b>רשיונות '
                'מיוחדים</b>;</li>\r\n'
                '    <li>הכנת <b>תגובות להצעות מדיניות</b> של משרד '
                'התקשורת;</li>\r\n'
                '    <li>התדיינות עם הרשות להגבלים עסקיים ומשרד התקשורת על פעילות '
                'בעלי מונופולים בתחום התקשורת;</li>\r\n'
                '    <li>הסדרת תקשורת ב<b>חקיקה</b>: במסגרת זאת ליווינו מטעמם של '
                'ספקי גישה לאינטרנט חלק מתהליך התיקון לחוק התקשורת (בזק '
                'ושידורים);</li>\r\n'
                '    <li><b>הסכמי-תקשורת</b> (כדוגמת הסכמים לרכישת שירותי לווין, '
                'קווי תקשורת); ועוד.</li>\r\n'
                '</ul>',
     'language': 'he',
     'order': 3,
     'slug': 'communications',
     'title': 'תקשורת'},
    {'content': 'היערכות לארועי סייבר וליווי לאחריהם; ייעוץ משפטי לחברות מסחריות '
                'ומיזמי אינטרנט, המבקשים ליישב בין האפשרויות הנרחבות של איסוף '
                'מידע אודות לקוחותיהם עם הוראות הדין.&nbsp;הפעילות בתחום זה כוללת '
                '-\r\n'
                '<ul>\r\n'
                '    <li>הכנת וביקורת מסמכי היערכות להתקפות מקוונות ואבדן '
                'מידע;</li>\r\n'
                '</ul>\r\n'
                '<ul>\r\n'
                '    <li>ליווי ארגונים ביעוץ משפטי לאחר מכן;</li>\r\n'
                '</ul>\r\n'
                '<ul>\r\n'
                '    <li>הכנת חוות דעת בסוגיות מגוונות, המיועדות להנחות את הארגון '
                'ביחס למותר ואסור ולסייע בקביעת כללי ניהול מאגרי מידע; <br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>גיבוש מדיניות פרטיות מוצהרת באתרי אינטרנט; <br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>ליווי הסכמים מסחריים, שיש בהם הבטים של הגנה על פרטיות '
                'ואבטחת מידע; <br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>מתן הדרכה לעובדים הרלבנטיים בחברות מסחריות, ביחס לכללים '
                'הרצויים בעת טיפול במידע אישי; ועוד. <br />\r\n'
                '    &nbsp;</li>\r\n'
                '</ul>\r\n'
                'הלקוחות בתחום זה כוללים -<br />\r\n'
                '<ul>\r\n'
                '    <li>חברות בינלאומיות המבקשות לוודא שפעילותן תואמת את הדין '
                'הורגולציה בישראל;</li>\r\n'
                '</ul>\r\n'
                '<ul>\r\n'
                '    <li>סטארטאפים וחברות-הזנק;</li>\r\n'
                '</ul>\r\n'
                '<ul>\r\n'
                '    <li>חברות וארגונים מהגדולים במשק הישראלי - ממוסדות פיננסים '
                'דרך ארגוני בריאות וכלה ברשתות חינוך;</li>\r\n'
                '</ul>\r\n'
                '<ul>\r\n'
                '    <li>Data Brokers - חברות המספקות שירותי דיוור ישיר;</li>\r\n'
                '</ul>',
     'language': 'he',
     'order': 4,
     'slug': 'cybersecurity-data-protection-and-privacy',
     'title': 'סייבר, אבטחת מידע ופרטיות'},
    {'content': '<p>הקבוצה מייצגת בתחומים אלה בעלי זכויות, המבקשים, מצד אחד, להגן '
                'על קניינם הרוחני ומצד שני להפיק ממנו את התועלת הכלכלית המרבית '
                'על-ידי גיבוש הסדרי רישוי נכונים - וכן את מי שמבקשים להשתמש כדין '
                'בקניינם הרוחני של אחרים. פעילותה בתחום זה מקיפה, בין השאר '
                '-</p>\r\n'
                '<ul>\r\n'
                '    <li>ייצוג בעלי זכויות בהתקשרות עם גופים וחברות המבקשים '
                'להשתמש ביצירותיהם בכלל - ובאינטרנט ובתקשורת מתקדמת בפרט;</li>\r\n'
                '    <li>הגנה על זכויות יוצרים ואכיפת קניין רוחני;</li>\r\n'
                '    <li>חוות דעת בסוגיות של יישום דיני קניין רוחני בכלל ובתחומי '
                'המחשב והאינטרנט בפרט;</li>\r\n'
                '    <li>סיוע בגיבוש מדיניות בדבר שימוש בקניינים רוחניים (כדוגמת '
                'צילומים, יצירות מוסיקליות וסרטים);</li>\r\n'
                '    <li>הכנת הסכמים, שיהוו אבות-טיפוס לרשיונות שיעניקו בעלי '
                'זכויות היוצרים;</li>\r\n'
                '    <li>הליכים משפטיים;</li>\r\n'
                '</ul>',
     'language': 'he',
     'order': 5,
     'slug': 'intellectual-property-and-copyright-licensing',
     'title': 'זכויות יוצרים'},
    {'content': '<p>The implementation of information technology into businesses '
                'and companies, use of the Internet and e-commerce, raise legal '
                'issues that combine diverse legal areas otherwise rarely to be '
                'found together: intellectual property, privacy laws, consumer '
                'protection, contract law, evidence law, etc.  <br />\r\n'
                '<br />\r\n'
                'Services provided by the Internet, IT &amp; Copyright group at '
                '<a href="http://www.pczlaw.com">Pearl Cohen Zedek Latzer</a> '
                'include:</p>\r\n'
                '<ul>\r\n'
                '    <li>E-commerce and content project management, from initial '
                'characterization all the way to up-and-running application. The '
                'group attorneys has acquired a great deal of experience in '
                'handling contracts with application providers, content partners '
                'and information suppliers, and in handling negotiations leading '
                'up to signing the contracts; assessing and reducing the legal '
                'risks entailed in operating the systems; checking the sites and '
                'the processes there prior to launching; providing counseling '
                'regarding legal aspects of information and privacy protection in '
                'such systems, etc.<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>Drawing up contracts - online or other - as well as '
                'terms of use and privacy policies for Internet sites, both '
                'business-to-customer (B2C) or business-to-businesses (B2B). The '
                'group advises its clients on the proper way to o implement such '
                'agreements, and whether to choose online contracts or standard '
                'ones;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>contracts for constructing and marinating Internet sites '
                'and systems;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>Agreements for content provision, designed for both the '
                'Web &amp; cellular media;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>Litigation: Amongst its cases, the group handled a first '
                'suit of its kind - an Internet service provider vs. the Israel '
                'Defense Forces (IDF) - pertaining to a court order to the '
                'service provider to supply the IDF with the e-mail '
                'correspondence of its subscribers. This precedent ended with the '
                'State Attorney accepting a substantial number of the claims made '
                'by the service provider and recognizing that intercepting e-mail '
                "messages before they have reached the provider's computers is "
                'wiretapping and therefore permitted only with a court order '
                'designated to electronic eavesdropping. The group represents '
                'another provider in the first suit brought against a spammer in '
                'Israel. Other cases the group professionals handled involved '
                'domain names dispute, copyright infringements, etc.<br />\r\n'
                '    &nbsp;</li>\r\n'
                "    <li>Legal opinions: the issues dealt with by the group's "
                'attorneys in recent years include legal risks entailed in '
                'managing Internet activity or developing certain software; the '
                "do's and don'ts of web linking; aspects of intellectual property "
                'in software; protection of intellectual property in the digital '
                'environment and appropriate licensing; application of privacy '
                'laws and consumer protection laws to certain areas of '
                'e-commerce; application of the Israeli Encryption Order to '
                'certain online activities; application and interpretation of '
                'open source code licenses to software development, etc. <br '
                '/>\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>Copyright enforcement.</li>\r\n'
                '</ul>',
     'language': 'en',
     'order': 0,
     'slug': 'internet-law',
     'title': 'Internet Law'},
    {'content': '<p>Computers and Information Technology lie at the core of any '
                'business. The Internet, Cyber &amp; Copyright group at <a '
                'href="http://www.pczlaw.com">Pearl Cohen</a>&nbsp;has experience '
                'in drafting the agreements needed for acquisition, development '
                'and operation of IT and other telecommunications transactions, '
                'including:</p>\r\n'
                '<ul>\r\n'
                '    <li>initial involvement: preparation of '
                '<strong>RFIs</strong>, <strong>RFPs</strong>, <strong>Public '
                'Tenders</strong> and handling negotiations;</li>\r\n'
                '    <li>Software as a Service (<strong>SaaS</strong>) &amp; '
                '<strong>Cloud Computing</strong> Agreements;</li>\r\n'
                '    <li>agreements for d<strong>evelopment &amp; '
                'maintenance</strong> of software</li>\r\n'
                '    <li><strong>outsourcing </strong>agreements;</li>\r\n'
                '</ul>\r\n'
                '<p>Transactions handled by the group range from tens of '
                'thousands of dollars, to millions.</p>',
     'language': 'en',
     'order': 1,
     'slug': 'computers-and-IT',
     'title': 'Computers, Information Systems & Technology acquistion'},
    {'content': '<p>In 2000-2001, the firm was actively involved in the '
                'legislation of the Electronic Signature Law. During the process '
                'itself, Advocate Haim Ravia served as the Israel Bar '
                "Association's representative to the Knesset sub-committee, and "
                'also followed closely the regulatory developments.  <br />\r\n'
                '<br />\r\n'
                'The Internet, IT &amp; Copyright group at <a '
                'href="http://www.pczlaw.com">Pearl Cohen Zedek Latzer</a> '
                'currently represent one of the two Certificate Authorities '
                'operating in Israel. The group also consults companies '
                'developing Digital Signature systems and organizations that wish '
                'to implement such systems in their day-to-day activities.</p>',
     'language': 'en',
     'order': 2,
     'slug': 'e-sig',
     'title': 'Electronic Signature'},
    {'content': '<p>The Internet, IT &amp; Copyright group at <a '
                'href="http://www.pczlaw.com">Pearl Cohen Zedek Latzer</a> '
                'represent and advise clients on a variety of communications '
                'issues, including:</p>\r\n'
                '<ul>\r\n'
                '    <li>negotiations with the Ministry of Communications for '
                'special licensing agreements;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>drafting replies to policy papers issued by the Ministry '
                'of Communications, and drafting submission to the Ministry of '
                'Communications to review before making policy decisions, on '
                'matters of technological innovation;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>deliberations with the Antitrust Authority and the '
                'Ministry of Communication on the activity of communications '
                'monopolies;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>Communications agreements (such as acquisition of '
                'satellite services, telecommunications cables, etc.)</li>\r\n'
                '</ul>\r\n'
                "<p>Amongst the groups's clients in this field of expertise is "
                'one of the Israeli providers of international telephone '
                'services.</p>',
     'language': 'en',
     'order': 3,
     'slug': 'communications',
     'title': 'Communications'},
    {'content': '<p>The Israeli Privacy Law differs from the U.S. and European '
                'arrangements. It is also older than most of them, dating back to '
                '1981. The Internet, IT &amp; Copyright group at <a '
                'href="http://www.pczlaw.com">Pearl Cohen Zedek Latzer</a> '
                'provide legal counseling on Privacy and Data Protection to '
                'companies and ventures seeking to reconcile exploiting the vast '
                'possibilities of gathering information about their clients with '
                'the provisions of the law. Activity in this area includes</p>\r\n'
                '<ul>\r\n'
                '    <li>drafting opinions on a variety of issues, with the '
                "purpose of guiding the organization through the do's and don'ts "
                'of this area;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>assisting with the formulation of rules for the '
                'management of databases;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>formulating privacy policies for Internet sites;<br '
                '/>\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>advising on commercial agreements that include aspects '
                'of information and privacy protection;<br />\r\n'
                '    &nbsp;</li>\r\n'
                '    <li>training relevant employees in commercial companies to '
                'adopt responsible practices for handling  personal information, '
                'etc.</li>\r\n'
                '</ul>\r\n'
                '<p>This special area of expertise at the group, headed by <a '
                'href="/en/office/lawyers/or-hof/">Advocate Dan Or-Hof</a>.</p>',
     'language': 'en',
     'order': 4,
     'slug': 'intellectual-property-and-copyright-licensing',
     'title': 'Intellectual Property & Copyright licensing'},
    {'content': '<meta content="text/html; charset=utf-8" '
                'http-equiv="Content-Type">\r\n'
                '<meta content="Word.Document" name="ProgId">\r\n'
                '<meta content="Microsoft Word 11" name="Generator">\r\n'
                '<meta content="Microsoft Word 11" name="Originator">\r\n'
                '<link '
                'href="file:///C:%5CDOCUME%7E1%5CRAVIA%7E1.PCZ%5CLOCALS%7E1%5CTemp%5Cmsohtml1%5C01%5Cclip_filelist.xml" '
                'rel="File-List" /><!--[if gte mso 9]><xml>\r\n'
                '<w:WordDocument>\r\n'
                '<w:View>Normal</w:View>\r\n'
                '<w:Zoom>0</w:Zoom>\r\n'
                '<w:PunctuationKerning />\r\n'
                '<w:ValidateAgainstSchemas />\r\n'
                '<w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>\r\n'
                '<w:IgnoreMixedContent>false</w:IgnoreMixedContent>\r\n'
                '<w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>\r\n'
                '<w:Compatibility>\r\n'
                '<w:BreakWrappedTables />\r\n'
                '<w:SnapToGridInCell />\r\n'
                '<w:WrapTextWithPunct />\r\n'
                '<w:UseAsianBreakRules />\r\n'
                '<w:DontGrowAutofit />\r\n'
                '</w:Compatibility>\r\n'
                '<w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>\r\n'
                '</w:WordDocument>\r\n'
                '</xml><![endif]--><!--[if gte mso 9]><xml>\r\n'
                '<w:LatentStyles DefLockedState="false" '
                'LatentStyleCount="156">\r\n'
                '</w:LatentStyles>\r\n'
                '</xml><![endif]--><style type="text/css">\r\n'
                '<!--\r\n'
                ' /* Font Definitions */\r\n'
                ' @font-face\r\n'
                '\t{font-family:Wingdings;\r\n'
                '\tpanose-1:5 0 0 0 0 0 0 0 0 0;\r\n'
                '\tmso-font-charset:2;\r\n'
                '\tmso-generic-font-family:auto;\r\n'
                '\tmso-font-pitch:variable;\r\n'
                '\tmso-font-signature:0 268435456 0 0 -2147483648 0;}\r\n'
                '@font-face\r\n'
                '\t{font-family:David;\r\n'
                '\tpanose-1:0 0 0 0 0 0 0 0 0 0;\r\n'
                '\tmso-font-charset:177;\r\n'
                '\tmso-generic-font-family:auto;\r\n'
                '\tmso-font-pitch:variable;\r\n'
                '\tmso-font-signature:6145 0 0 0 32 0;}\r\n'
                '@font-face\r\n'
                '\t{font-family:Verdana;\r\n'
                '\tpanose-1:2 11 6 4 3 5 4 4 2 4;\r\n'
                '\tmso-font-charset:0;\r\n'
                '\tmso-generic-font-family:swiss;\r\n'
                '\tmso-font-pitch:variable;\r\n'
                '\tmso-font-signature:536871559 0 0 0 415 0;}\r\n'
                ' /* Style Definitions */\r\n'
                ' p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n'
                '\t{mso-style-parent:"";\r\n'
                '\tmargin:0cm;\r\n'
                '\tmargin-bottom:.0001pt;\r\n'
                '\ttext-align:right;\r\n'
                '\tmso-pagination:widow-orphan;\r\n'
                '\tdirection:rtl;\r\n'
                '\tunicode-bidi:embed;\r\n'
                '\tfont-size:12.0pt;\r\n'
                '\tfont-family:"Times New Roman";\r\n'
                '\tmso-fareast-font-family:"Times New Roman";\r\n'
                '\tmso-bidi-font-family:David;}\r\n'
                '@page Section1\r\n'
                '\t{size:612.0pt 792.0pt;\r\n'
                '\tmargin:72.0pt 90.0pt 72.0pt 90.0pt;\r\n'
                '\tmso-header-margin:36.0pt;\r\n'
                '\tmso-footer-margin:36.0pt;\r\n'
                '\tmso-paper-source:0;}\r\n'
                'div.Section1\r\n'
                '\t{page:Section1;}\r\n'
                ' /* List Definitions */\r\n'
                ' @list l0\r\n'
                '\t{mso-list-id:330330160;\r\n'
                '\tmso-list-type:hybrid;\r\n'
                '\tmso-list-template-ids:1748000500 67698693 67698691 67698693 '
                '67698689 67698691 67698693 67698689 67698691 67698693;}\r\n'
                '@list l0:level1\r\n'
                '\t{mso-level-number-format:bullet;\r\n'
                '\tmso-level-text:\uf0a7;\r\n'
                '\tmso-level-tab-stop:36.0pt;\r\n'
                '\tmso-level-number-position:left;\r\n'
                '\ttext-indent:-18.0pt;\r\n'
                '\tfont-family:Wingdings;}\r\n'
                'ol\r\n'
                '\t{margin-bottom:0cm;}\r\n'
                'ul\r\n'
                '\t{margin-bottom:0cm;}\r\n'
                '-->\r\n'
                '</style><!--[if gte mso 10]>\r\n'
                '<style>\r\n'
                '/* Style Definitions */\r\n'
                'table.MsoNormalTable\r\n'
                '{mso-style-name:"טבלה רגילה";\r\n'
                'mso-tstyle-rowband-size:0;\r\n'
                'mso-tstyle-colband-size:0;\r\n'
                'mso-style-noshow:yes;\r\n'
                'mso-style-parent:"";\r\n'
                'mso-padding-alt:0cm 5.4pt 0cm 5.4pt;\r\n'
                'mso-para-margin:0cm;\r\n'
                'mso-para-margin-bottom:.0001pt;\r\n'
                'mso-pagination:widow-orphan;\r\n'
                'font-size:10.0pt;\r\n'
                'font-family:"Times New Roman";\r\n'
                'mso-ansi-language:#0400;\r\n'
                'mso-fareast-language:#0400;\r\n'
                'mso-bidi-language:#0400;}\r\n'
                '</style>\r\n'
                '<![endif]-->\r\n'
                '<p style="text-align: justify; line-height: 14pt; direction: '
                'ltr; unicode-bidi: embed;" class="MsoNormal"><span '
                'style="font-size: 10pt; font-family: Verdana;">The group has '
                'accumulated vast experience in various aspects of OSS (Open '
                'Source Software):</span><span style="font-size: 10pt; '
                'font-family: Verdana;"><o:p>&nbsp;</o:p></span></p>\r\n'
                '<ul type="square" style="margin-top: 0cm;">\r\n'
                '    <li style="margin-right: 0cm; margin-left: 36pt; text-align: '
                'justify; line-height: 14pt; direction: ltr; unicode-bidi: '
                'embed;" class="MsoNormal"><span style="font-size: 10pt; '
                'font-family: Verdana;">Legal advice regarding the way to use '
                'popular OSS      (such as MySQL) while both respecting its '
                'license and marinating the      confidentiality of your '
                'proprietary computer code;</span><span style="font-size: 10pt; '
                'font-family: Verdana;"><o:p></o:p></span></li>\r\n'
                '</ul>\r\n'
                '<ul type="square" style="margin-top: 0cm;">\r\n'
                '    <li style="margin-right: 0cm; margin-left: 36pt; text-align: '
                'justify; line-height: 14pt; direction: ltr; unicode-bidi: '
                'embed;" class="MsoNormal"><span style="font-size: 10pt; '
                'font-family: Verdana;">Integration of GPL &amp; LGPL software '
                'with      proprietary code;</span><span style="font-size: 10pt; '
                'font-family: Verdana;"><o:p>&nbsp;</o:p></span></li>\r\n'
                '</ul>\r\n'
                '<ul type="square" style="margin-top: 0cm;">\r\n'
                '    <li style="margin-right: 0cm; margin-left: 36pt; text-align: '
                'justify; line-height: 14pt; direction: ltr; unicode-bidi: '
                'embed;" class="MsoNormal"><span style="font-size: 10pt; '
                'font-family: Verdana;">Corporate Policies regarding use, '
                'development,      integration and distribution of '
                'OSS;</span><span style="font-size: 10pt; font-family: '
                'Verdana;"><o:p>&nbsp;</o:p></span></li>\r\n'
                '</ul>\r\n'
                '<ul type="square" style="margin-top: 0cm;">\r\n'
                '    <li style="margin-right: 0cm; margin-left: 36pt; text-align: '
                'justify; line-height: 14pt; direction: ltr; unicode-bidi: '
                'embed;" class="MsoNormal"><span style="font-size: 10pt; '
                'font-family: Verdana;">Legal proceedings: the group represented '
                'the      defendants in the precedent setting case of Marianovsky '
                'v. IChessU, before      the District Court of Tel-Aviv. The '
                'first case ever to deal with the      integration of GPL and '
                'proprietary codes, it ended in a confidential out-of-court      '
                'settlement.<o:p></o:p></span></li>\r\n'
                '</ul>\r\n'
                '</meta>\r\n'
                '</meta>\r\n'
                '</meta>\r\n'
                '</meta>',
     'language': 'en',
     'order': 0,
     'slug': 'open-source',
     'title': 'Open Source'},
    {'content': '<p class="MsoNormal">We leverage our nuanced understanding of '
                'new technologies and our experience in Internet, IT and Cyber '
                'law to offer our clients comprehensive legal services for the '
                'growing complexities of cyber, information and data privacy '
                'laws. <br />\r\n'
                '<br />\r\n'
                'In recent years, regulatory agencies are becoming more attuned '
                'to cyber and cyber-security, issuing various guidelines in this '
                'realm. The legal framework governing the use of IT systems at '
                'businesses is also significantly adjusting to cyber and '
                'cyber-security. Pearl Cohen&rsquo;s seasoned Cyber and Internet '
                'practice group fuses intimate knowledge of cyber law and cyber '
                'security regulations with deep technical and business '
                'understanding of cyber-oriented companies. We counsel clients on '
                'all legal aspects of their cyber operations and cyber-defense '
                'activities, and guide them on the measures they need to take in '
                'order to comply with the legal standards applicable to their '
                'activities in cyberspace<br />\r\n'
                '<br />\r\n'
                'One of the cornerstones of cyber personal information '
                'processing. Our approach in counselling on personal information '
                'processing recognizes that is a unique asset that clients can '
                'leverage to yield long-term business advantages, if the legal '
                'nuances it entails are properly and timely addressed. We '
                'regularly advise local and multinational corporations on the '
                'intricacies of data protection and privacy laws in various '
                'jurisdictions worldwide, and provide clients with '
                'all-encompassing legal support they need to manage and protect '
                'personal information. This includes:</p>\r\n'
                '<p class="MsoNormal"><o:p></o:p></p>\r\n'
                '<ul>\r\n'
                '    <li>Legal opinions and guidance on legal risk management on '
                'a variety of information privacy and data protection issues '
                'pertinent to businesses.<o:p></o:p></li>\r\n'
                '    <li>Guidance for data handlers on the best practices of '
                'collecting, storing and processing personal information in the '
                'context of websites, online services and mobile '
                'apps.<o:p></o:p></li>\r\n'
                '    <li>Assistance in the formulation of rules, procedures, '
                'guidelines and policies for the prudent management of databases '
                'and data processing activities.<o:p></o:p></li>\r\n'
                '    <li>Advice on negotiating commercial agreements that entail '
                'information privacy and data protection issues, including global '
                'considerations regarding data processing activities, the use of '
                'cloud services, and cross-border flow of '
                'information.<o:p></o:p></li>\r\n'
                '    <li>Counseling clients in the routine but error-prone, '
                'mandatory process of registering a database at the Israeli '
                'Registrar of Databases (the Israeli privacy regulator operating '
                'under the Israeli Law, Information and Technology Authority - '
                'ILITA).<o:p></o:p></li>\r\n'
                '    <li>Representing and counseling clients through '
                'investigative, supervisory and enforcement procedures conducted '
                'by the Israeli privacy regulator.<o:p></o:p></li>\r\n'
                '    <li>Training employees involved in data processing '
                'activities on procedures mandated by law, and recommended best '
                'practices in the fields of data protection and information '
                'privacy.<o:p></o:p></li>\r\n'
                '    <li>Representation in deliberations on bills in the Israeli '
                "Parliament's committees.<o:p></o:p></li>\r\n"
                '    <li>Litigation and legal representation in court proceedings '
                'involving data protection and privacy '
                'matters.<o:p></o:p></li>\r\n'
                '</ul>',
     'language': 'en',
     'order': 0,
     'slug': 'cyber-data-protection-and-privacy',
     'title': 'Cyber, Data Protection & Privacy'}
]


def load_practices(apps, schema_editor):
    Practice = apps.get_model('practices', 'PracticeArea')
    practices = [Practice(**page) for page in PRACTICES]
    Practice.objects.bulk_create(practices)


def unload_practices(apps, schema_editor):
    Practice = apps.get_model('practices', 'PracticeArea')
    slugs = set([x['slug'] for x in PRACTICES])
    Practice.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_practices, reverse_code=unload_practices)
    ]
