# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 18:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Knowledge Center',
                'verbose_name_plural': 'Knowledge Centers',
                'ordering': ('order', 'name'),
            },
        ),
    ]
