# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 09:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_commoncontent_email_notified'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCenterItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link to')),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='knowledge-centers', verbose_name='Attached file')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Video link from YouTube or Vimeo', null=True, verbose_name='Embedded Video')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_center_articles', to='content.Article', verbose_name='Article')),
                ('computer_law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_center_computer_laws', to='content.ComputerLaw', verbose_name='Computer Law')),
                ('knowledge_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge.KnowledgeCenter', verbose_name='Knowledge Center')),
                ('news_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_center_news', to='content.NewsItem', verbose_name='News Item')),
            ],
        ),
    ]
