# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 07:36
from __future__ import unicode_literals

from django.db import migrations

CENTERS = [
    {
        'name': 'חתימה אלקטרונית',
        'slug': 'e-sig',
        'description': '<p>תאור חתימה אלקטרונית</p>',
        'order': 1,
    },
    {
        'name': 'רשתות חברתיות',
        'slug': 'social-networks',
        'description': '<p>תאור רשתות חברתיות</p>',
        'order': 2,
    },
    {
        'name': 'פטנטים',
        'slug': 'patents',
        'description': '<p>תאור פטנטים</p>',
        'order': 3,
    },
]


def load_knowledge_centers(apps, schema_editor):
    Knowledge = apps.get_model('knowledge', 'KnowledgeCenter')
    centers = [Knowledge(**center) for center in CENTERS]
    Knowledge.objects.bulk_create(centers)


def unload_knowledge_centers(apps, schema_editor):
    Knowledge = apps.get_model('knowledge', 'KnowledgeCenter')
    slugs = set([x['slug'] for x in CENTERS])
    Knowledge.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge', '0002_knowledgecenteritems'),
    ]

    operations = [
        migrations.RunPython(load_knowledge_centers,
                             reverse_code=unload_knowledge_centers)
    ]
