# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledge_centers_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeCenterItems',
            new_name='KnowledgeCenterItem',
        ),
    ]
