# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20160920_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecenteritem',
            options={'verbose_name': 'Knowledge Center Item', 'verbose_name_plural': 'Knowledge Center Items'},
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='small_photo',
            field=models.ImageField(blank=True, help_text='Preferably at size of 583x177', null=True, upload_to='', verbose_name='Small Photo'),
        ),
        migrations.AlterField(
            model_name='knowledgecenter',
            name='photo',
            field=models.ImageField(blank=True, help_text='Preferably at size of 1166x370', null=True, upload_to='', verbose_name='Large Photo'),
        ),
    ]
