# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20160920_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecenter',
            name='photo',
            field=models.ImageField(blank=True, help_text='Preferably at size of 1168x370', null=True, upload_to='', verbose_name='Large Photo'),
        ),
    ]
