# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_auto_20160920_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecenteritem',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
    ]
