# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_knowledgecenteritem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
