# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 08:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_auto_20160923_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='In case of article, news or computer law, leave this blank', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='slug',
            field=models.SlugField(blank=True, help_text='In case of article, news or computer law, leave this blank', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='title',
            field=models.CharField(blank=True, help_text='In case of article, news or computer law, leave this blank', max_length=200, null=True, verbose_name='Title'),
        ),
    ]
