# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_auto_20160923_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecenteritem',
            name='display_in_listing',
            field=models.BooleanField(default=True, verbose_name='Display in listing'),
        ),
        migrations.AlterIndexTogether(
            name='knowledgecenteritem',
            index_together=set([('order', 'display_in_listing')]),
        ),
    ]
