# Generated by Django 4.2.24 on 2025-09-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_commoncontent_contributors_and_more'),
        ('knowledge', '0010_auto_20170325_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_center_articles', to='content.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='computer_law',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_center_computer_laws', to='content.computerlaw', verbose_name='Computer Law'),
        ),
        migrations.AlterField(
            model_name='knowledgecenteritem',
            name='news_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_center_news', to='content.newsitem', verbose_name='News Item'),
        ),
    ]
